// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB21MPPEvDG-H2fFeSymiKmQnqls1CAX4A',
    appId: '1:677659661798:web:7aae934870d44fab3df227',
    messagingSenderId: '677659661798',
    projectId: 'zakhira-46d1e',
    authDomain: 'zakhira-46d1e.firebaseapp.com',
    storageBucket: 'zakhira-46d1e.appspot.com',
    measurementId: 'G-58TZWMT87G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYeSqp3jrB4nx-dTsDzZvtVwqgY9Z-Jts',
    appId: '1:677659661798:android:cb84f6bb60285a463df227',
    messagingSenderId: '677659661798',
    projectId: 'zakhira-46d1e',
    storageBucket: 'zakhira-46d1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFdpGgz59a0umpR6LoBGgrBudfMNutuI0',
    appId: '1:677659661798:ios:ab6eb73dd5c1c3073df227',
    messagingSenderId: '677659661798',
    projectId: 'zakhira-46d1e',
    storageBucket: 'zakhira-46d1e.appspot.com',
    iosClientId: '677659661798-65d4apc2bpia3h505mro7hv054j5hiq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.zakira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFdpGgz59a0umpR6LoBGgrBudfMNutuI0',
    appId: '1:677659661798:ios:ab6eb73dd5c1c3073df227',
    messagingSenderId: '677659661798',
    projectId: 'zakhira-46d1e',
    storageBucket: 'zakhira-46d1e.appspot.com',
    iosClientId: '677659661798-65d4apc2bpia3h505mro7hv054j5hiq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.zakira',
  );
}
